### PR TITLE
Ignore `:httpc` missing compilation warning

### PR DESCRIPTION
**Pull request by danschultzer**
Resolves https://github.com/danschultzer/premailex/issues/55

### CODE REVIEW

**Comment by altdsoy** [comment]
Hello Dan..
I don't know why but take a look..
This is the file I got when doing `mix deps.get` (extract):
```elixir
defmodule Premailex.Mixfile do
  use Mix.Project

  @version "0.3.11"

  def project do
    [
      app: :premailex,
      version: @version,
      elixir: "~> 1.6",
      start_permanent: Mix.env() == :prod,
      deps: deps(),

      # Hex
      description: "Add inline styling to your HTML emails, and transform them to text",
      package: package(),

      # Docs
      name: "Premailex",
      docs: docs(),

      xref: [exclude: [Meeseeks, Meeseeks.Document, Meeseeks.Selector.CSS, :certifi, :ssl_verify_hostname]]
    ]
  end
...
```

Look ho I correctly got `@version "0.3.11"` while still having the old array for the `xref:`..
I wonder where is the problem from..
I already cleared the deps and _build folder..
Since I'm working with Docker, I'll try to wipe and rebuild the docker containers too, but I don't think it's related to docker..

**Comment by danschultzer** [comment]
Sorry, not in a release. Let me get one ready. Until then you can use the master branch: `{:premailex, github: "danschultzer/premailex"}`.

**Comment by altdsoy** [comment]
No problem.. I was just thinking that the version shown in hex.pm should match the tag in github (or simply the version shown in `mix.exs`)

So I understand that when you will push that on hex.pm you'll mostly likely also bump the version at that moment..

**Comment by danschultzer** [comment]
Yeah, exactly, master is development and I first bump the version whenever I'm close to releasing. `v0.3.12` has been released now 😄

**Pull request merged**
