### PR TITLE
Fix whitespace loss, retain doctypes, remove inlined styles from HEAD

### PR DESCRIPTION
**Pull request by willbarrett**
Hey @danschultzer - I've tweaked the functionality described in issue #8 , and added some test cases. Happy to discuss this work! Here's the high-level:

### Improvements:
- Retain whitespace between tags when inlining CSS
    - Important for inline tags, e.g. `<b>this space</b> <i>should be respected</i>`
    - Makes the generated markup far more readable
- Retain doctypes when inlining CSS
    - Some mail clients parse mail differently based on doctype
- Allows the user to specify the CSS used to lookup style elements
    - Sometimes templates have both CSS included in the HEAD, and inlined CSS, and these two things can be different.
    - Greater flexibility for the lib.
- Remove inlined styles from document HEAD after inlining
    - Reduces bandwidth usage, less template to read :)

### TODO
- [ ] Currently the meeseeks dependency is pinned (to a branch)[https://github.com/mischov/meeseeks/pull/35]. This will not be necessary (as soon as the next version of meeseeks is released)[https://github.com/mischov/meeseeks/pull/35#issuecomment-381240080]

### Why Meeseeks?
Currently, there isn't a sane HTML parser written in Elixir or Erlang, according to multiple places on the interwebs, and copious research. Meeseeks provides a good wrapper and nice functionality around the html5ever parser, written in Rust, and the maintainer's a super-smart super-helpful guy. The main bug being fixed here, the missing whitespace between tags, will result in broken display for most users of this library at some point. I think it's worth moving to a different parser for the functionality necessary to resolve the issue.

### CODE REVIEW

**Comment by willbarrett** [comment]
CI failure is due to Travis failing when pulling the meeseeks dependency from Github. Not sure what that's about, as deps are pulled successfully locally. Tests are passing locally. The next release of meeseeks will be compatible with this change.

**Comment by danschultzer** [comment]
I've opened #10, but it'll require rebasing of this branch.

**Comment by willbarrett** [comment]
Nice. I'll rebase + follow that approach Monday.

**Comment by danschultzer** [comment]
Sorry, got busy with some unrelated work. I've merged in #11, and I'll start to work on the issues you've highlighted.

**Comment by danschultzer** [comment]
FYI, I've worked on the whitespace issue in https://github.com/danschultzer/premailex/pull/12. From what I've read, we want to preserve whitespace only when child elements consists of text nodes and inline-block nodes. So I've let Premailex taken care of the quirks in both Meeseeks and Floki.

**Comment by willbarrett** [comment]
In our case, the full readable whitespace is desirable - premailex is just one step of a long compilation process, so we'd like the result to be readable rather than fully concatenated. Perhaps we could add an option to retain all whitespace vs. only the lexically-relevant whitespace?

**Comment by danschultzer** [comment]
That makes sense, I'll update #12 with the option to retain all whitespace.

**Comment by willbarrett** [comment]
OK, cool. Since you're working on that changeset, is there a part of this that you'd like me to break off into a separate PR? I'd be happy to help out since I brought the issues to light.

**Comment by danschultzer** [comment]
That would be great! I prefer to keep the PR's small, so if you could break this one up into separate PR's:

- Remove inline style tags
- Option to specify CSS style tag selector
- Retain doctypes

**Comment by willbarrett** [comment]
Awesome. I've got a bunch of PR reviews to get to, but I'll open at least one of those this afternoon. Retaining doctypes is somewhat harder under Floki. Is it acceptable if some of these changes require Meeseeks to work properly?

**Comment by danschultzer** [comment]
Yeah, it's acceptable.

**Comment by willbarrett** [comment]
Nice. Yesterday afternoon went sideways, hopefully I'll have a PR for you this AM.

**Pull request closed without merging**
