### PR TITLE
tbody with class does not make it to output

### PR DESCRIPTION
**Pull request by backspace**
This amends the existing test to show that a `tbody` with a `class` attribute is not part of the final output. I didn’t immediately see what might be needed to get this working but I’ll look at it more in the future 🤞🏻

### CODE REVIEW

**Comment by backspace** [comment]
I still can’t figure out where attributes would be causing a problem. I also found that a `data-test-*` attribute caused the same problem so it’s not specific to `class` 🤔

**Comment by danschultzer** [comment]
Thanks, didn't realize that there was a match on the attributes. I've fixed it now and added a test that ensures this get caught in the future for any new elements or during refactors.

**Comment by danschultzer** [comment]
v0.3.18 is out with this fix!

**Comment by backspace** [comment]
thank you 🎉

**Pull request merged**
